const constants = {
  toast: {
    ADD_SUCCESS_MSG: "item successfully added",
    WEB_UPDATE_SUCCESS_MSG: "The data for the web catalog has been updated.",
    UPDATE_SUCCESS_MSG: "item successfully updated",
    UPDATE_DB_ERR_MSG: "Please check your fields, no rows have been updated.",
    DELETE_CONFIRM_MSG: "Are you sure you want to delete this item?",
    DELETE_ABORT_MSG: "Delete aborted.",
    valErr: {
      NO_EMPTY_FIELDS_MSG: "All fields must be filled out.",
      YEAR_FORMAT_MSG: "Year must be 4 digits",
      YEAR_TYPE_MSG: "Year must be a number.",
      NO_TRACKS_MSG: "Please add some tracks.",
      LOCATION_INVALID_MSG: "Location field does not contain a valid value.",
      NO_LOC_SEL_INCR_MSG: "Select a location to increment first.",
      NO_INCR_AVAIL_MSG: "That location can not be incremented.",
      NO_ACTIVE_FORM_MSG: "Please load a format's entry form first.",
      FORM_MISMATCH_MSG:
        "The active form does not match the format of the last entry.",
      TRACK_FORMAT_MSG: "Check your track data. Must be <artist>|<title>.",
      NO_ARTIST_MSG: "All tracks must have an artist",
      NO_TRACKNAME_MSG: "All tracks must have a track name",
      UPDATE_NO_ID_MSG: "Please enter an id to update.",
      UPDATE_NO_SEL_FORMAT_MSG: "Please select a format to update an item.",
      LOOKUP_NO_FIELD_MSG: "Please select a field to search.",
      LOOKUP_NOT_VALID_NUM_MSG:
        "Please enter a valid number to search by that field.",
      LOOKUP_YEAR_RANGE_MSG:
        "Please enter a valid 4 digit year between 1885 and the current year.",
      UPDATE_TRACKS_NO_DELETE:
        "Can not DELETE tracks here yet, only update or add.",
    },
    ERROR_NO_COMPS_MSG: "No Cd-Compilations found with that id.",
    ERROR_NO_SINGLES_MSG: "No Cd-Singles found with that id.",
    ERROR_NO_CDS_MSG: "No Cds found with that id.",
    ERROR_NO_RECORDS_MSG: "No Records found with that id.",
    ERROR_NO_TAPES_MSG: "No Tapes found with that id.",
  },
  data: {
    CDS_TEST_LOC_VAL_NO_NUM: "test_location_no_num",
    CDS_TEST_LOC_VAL_W_NUM: "test_location_w_num 1",
    CDS_TEST_LOC_VAL_W_INCR_NUM: "test_location_w_num 2",
    INVALID_LOCATION: "INVALID LOCATION NAME",
    VALID_LOCATION: "Good Location 47",
    UPDATE_VALID_LOCATION: "Soundtrack 1",
    INVALID_FORMAT_YEAR: "19805",
    INVALID_TYPE_YEAR: "Unicorn",
    VALID_FORMAT_YEAR: "1980",
    VALID_ARTIST: "Test Artist",
    VALID_ARTIST_2: "Test Artist 2",
    VALID_TITLE: "Test Title",
    VALID_RECORD_LABEL: "Test Label",
    VALID_COMP_TRACK: "artist name|track name",
    VALID_SINGLES_TRACK: "trackname",
    VALID_TRACKNAME: "Test Trackname",
    VALID_TRACKNAME_2: "Test Trackname 2",
    MOCK_CD_DATA: {
      id: "id: 4747",
      artist: "MOCK CD MAIN ARTIST",
      title: "MOCK CD MAIN TITLE",
      location: "Jazz 1",
    },
    WEB_DATA_KEYS_CDS: ["id", "artist", "title", "location"],
    WEB_DATA_KEYS_TAPES: [
      "id",
      "artist",
      "title",
      "location",
      "year",
      "needs_repair",
      "speed",
    ],
    WEB_DATA_KEYS_RECORDS: [
      "id",
      "artist",
      "title",
      "location",
      "year",
      "diameter",
      "sleeve_condition",
      "record_condition",
      "label",
    ],
    WEB_DATA_KEYS_CD_SINGLES_TRACKS: ["track_id", "track_name", "single_id"],
    WEB_DATA_KEYS_CD_SINGLES: [
      "single_id",
      "artist",
      "title",
      "year",
      "case_type",
    ],
    WEB_DATA_KEYS_CD_COMPS_TRACKS: [
      "artist",
      "track_name",
      "title_id",
      "track_id",
    ],
    WEB_DATA_KEYS_CD_COMPS: ["title_id", "title", "year", "location"],
    FORM_ID_CD_COMPS: "cd-comps-form",
    FORM_ID_CD_SINGLES: "cd-singles-form",
    FORM_ID_CD_MAIN: "cd-main-form",
    FORM_ID_RECORDS: "records-form",
    FORM_ID_TAPES: "tapes-form",
    UPDATE_TEST_TEXT_VAL_1: "TEST VALUE ONE",
    UPDATE_TEST_TEXT_VAL_2: "TEST VALUE TWO",
    UPDATE_TEST_ITEM_ID: 1e9 - 1,
    UPDATE_ID_FORM_TEST_VALID_ID: "1",
  },
  pageTitle: {
    UPDATE_PAGE_TITLE: "The Majewski Collection Update Items",
    ADD_PAGE_TITLE: "The Majewski Collection Add Items",
  },
  color: {
    ERROR: "red",
    SUCCESS: "green",
  },
};

const updateFormVals = {
  UPDATE_TEST_ITEM_CD_COMP: {
    title_id: constants.data.UPDATE_TEST_ITEM_ID,
    title: constants.data.UPDATE_TEST_TEXT_VAL_1,
    year: new Date().getFullYear().toString(),
    location: constants.data.VALID_LOCATION,
    tracks: [
      constants.data.VALID_ARTIST,
      constants.data.VALID_TRACKNAME,
      constants.data.VALID_ARTIST_2,
      constants.data.VALID_TRACKNAME_2,
    ],
  },
  UPDATE_TEST_ITEM_CD_SINGLE: {
    single_id: constants.data.UPDATE_TEST_ITEM_ID,
    artist: constants.data.UPDATE_TEST_TEXT_VAL_1,
    title: constants.data.UPDATE_TEST_TEXT_VAL_1,
    year: new Date().getFullYear().toString(),
    case_type: "Digipack",
    tracks: [constants.data.VALID_SINGLES_TRACK],
  },
  UPDATE_TEST_ITEM_CDS: {
    id: constants.data.UPDATE_TEST_ITEM_ID,
    artist: constants.data.UPDATE_TEST_TEXT_VAL_1,
    title: constants.data.UPDATE_TEST_TEXT_VAL_1,
    location: constants.data.VALID_LOCATION,
  },
  UPDATE_TEST_ITEM_RECORDS: {
    id: constants.data.UPDATE_TEST_ITEM_ID,
    artist: constants.data.UPDATE_TEST_TEXT_VAL_1,
    title: constants.data.UPDATE_TEST_TEXT_VAL_1,
    location: constants.data.VALID_LOCATION,
    year: new Date().getFullYear().toString(),
    diameter: "12 inch",
    sleeve_condition: "***",
    record_condition: "***",
    label: constants.data.UPDATE_TEST_TEXT_VAL_1,
  },
  UPDATE_TEST_ITEM_TAPES: {
    id: constants.data.UPDATE_TEST_ITEM_ID,
    artist: constants.data.UPDATE_TEST_TEXT_VAL_1,
    title: constants.data.UPDATE_TEST_TEXT_VAL_1,
    location: constants.data.VALID_LOCATION,
    year: new Date().getFullYear().toString(),
    needs_repair: "No",
    speed: "na",
  },
};

export { updateFormVals };
export default constants;
